# Generated by Django 2.1.5 on 2019-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('phone', models.IntegerField()),
                ('distance', models.IntegerField(default=None)),
                ('notify', models.BooleanField(default=False)),
                ('image', models.URLField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
