# Generated by Django 2.1.5 on 2019-01-28 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
    ]
